### ISSUE TITLE
data.json

### ISSUE THREAD

**Issue by 460N1** [bgeVam/Kosovo-Coronatracker-Data#5]
Faqa nuk po funksionon momentalisht sepse data.json ne rreshtin e fundit tek deaths, nuk ka asni vler dhe tenton me parse '}' si vler. Vendosne 0 apo sado vdekje qe ka pas.
Peace out :P

**Comment by TriumfM** [comment]
Pershendetje Agon,faleminderit per informacion, tash eshte ne rregull.Me te mirat,Triumf Maqedonci.On 18 Jun 2020 09:50, Agon Hoxha <notifications@github.com> wrote:
Faqa nuk po funksionon momentalisht sepse data.json ne rreshtin e fundit tek deaths, nuk ka asni vler dhe tenton me parse '}' si vler. Vendosne 0 apo sado vdekje qe ka pas.
Peace out :P
