### ISSUE TITLE
gender chart

### ISSUE THREAD

**Issue by 460N1** [bgeVam/Kosovo-Coronatracker-Data#6]
gender chart nuk shfaq accurately. maybe per shkak qe ka raste ku nuk eshte raportu gjinia apo qfaredo arsye, po shuma e totalMale+totalFemale ne piechart zakonisht ~88, jo 100 qysh ish duft me kane

vendose

```
  var total=(totalMale+totalFemale)/100;
  totalMale=Math.round(totalMale/total);
  totalFemale=Math.round(totalFemale/total);
```

para var pieChart ne main.js qe tani shuma e tyne me kane 100

**Comment by TriumfM** [comment]
Te dhenat per gjinin e paicenteve te semur nuk po i bejne publike as Ministria as Insituti i shendetit publik!
