### ISSUE TITLE
age chart

### ISSUE THREAD

**Issue by 460N1** [bgeVam/Kosovo-Coronatracker-Data#7]
totali i age chart nuk arrin ne 100, vetem 86. maybe se ka raste kur raportohen qe nuk eshte specifiku mosha, ngjajshem me rast te gjinise.
shto ne main.js para 'ageChart = new Chart.......'

```
  var ageHistogramTotalMod=ageHistogram.reduce((a,b)=>a+b,0)/100;
  for(i=0;i<ageHistogram.length;i++){
	  ageHistogram[i]=Math.round(ageHistogram[i]/ageHistogramTotalMod);
  }
```

**Comment by TriumfM** [comment]
Te dhenat per moshen e paicenteve te semur nuk po i bejne publike as Ministria as Insituti i shendetit publik!
