### ISSUE TITLE
Forgotten comma issue

### ISSUE THREAD

**Issue by enharukalo** [bgeVam/Kosovo-Coronatracker-Data#8]
https://github.com/bgeVam/Kosovo-Coronatracker-Data/blob/master/patients.json#L34461

![image](https://user-images.githubusercontent.com/28190290/88458641-c9d44b80-ce8f-11ea-8c53-83506b783d41.png)

**Comment by TriumfM** [comment]
Faleminderit per kontributin. Gabimi u rregullua!
